import { IProduct } from "./types";

export const mock: IProduct[] = [
  {
    id: 1,
    name: "Ланч комбо",
    image: "/products/combo.png",
    price: 599,
    oldPrice: 1299,
    group: [7],
    color: "#FF6B35",
    variant: "big",
    subgroup: ["Комбо"],
    types: [
      {
        id: 1,
        name: "Стандарт",
        price: 599,
      },
    ],
    extras: null,
    information: {
      id: 1,
      composition: "Кимчи, фунчоза с овощами, напиток 0,5 л",
      description:
        "Кимчи, Фунчоза с печёными овощами в азиатском соусе, Напиток 0,5 л. на выбор",
      fats: 8,
      proteins: 11,
      carbohydrates: 32,
      calories: 270,
      gramm: "520 г",
    },
  },
  {
    id: 2,
    name: "Пицца BBQ",
    image: "/products/pizzaa.png",
    price: 979,
    oldPrice: 1299,
    group: [1],
    color: "#DC8F47",
    variant: "default",
    subgroup: ["Классика"],
    types: [
      { id: 1, name: "25 см", price: 979 },
      { id: 2, name: "30 см", price: 1099 },
      { id: 3, name: "35 см", price: 1199 },
    ],
    extras: [
      {
        id: 1,
        name: "Бекон",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Бекон",
      },
      {
        id: 2,
        name: "Курица",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Бекон",
      },
      {
        id: 3,
        name: "Лук",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Курица",
      },
      {
        id: 4,
        name: "Соус BBQ",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Соус BBQ",
      },
      {
        id: 5,
        name: "Сыр",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Сыр",
      },
      {
        id: 6,
        name: "Халапеньо",
        image: "/products/pizzaa.png",
        price: 100,
        description: "Халапеньо",
      },
    ],
    information: {
      id: 2,
      composition: "Тесто, томатный соус, моцарелла, соус BBQ, пепперони",
      description: "Сочная пицца с соусом BBQ и пикантной пепперони.",
      fats: 12,
      proteins: 14,
      carbohydrates: 33,
      calories: 280,
      gramm: "520 г",
    },
  },
  {
    id: 3,
    name: "Цезарио",
    image: "/products/salad.png",
    price: 979,
    oldPrice: 1299,
    group: [2],
    color: "#166C1D",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "Порция", price: 979 }],
    extras: null,
    information: {
      id: 3,
      composition: "Салатные листья, курица, помидоры, сыр, соус",
      description: "Свежий салат с курицей, помидорами и нежным соусом.",
      fats: 7,
      proteins: 10,
      carbohydrates: 6,
      calories: 150,
      gramm: "520 г",
    },
  },
  {
    id: 4,
    name: "Блинчики",
    image: "/products/blini.png",
    price: 129,
    oldPrice: null,
    group: [3],
    color: "#FFD700",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "Порция", price: 129 }],
    extras: null,
    information: {
      id: 4,
      composition: "Мука, яйца, молоко, сахар",
      description: "Нежные блинчики, идеальны к чаю.",
      fats: 5,
      proteins: 6,
      carbohydrates: 20,
      calories: 180,
      gramm: "520 г",
    },
  },
  {
    id: 5,
    name: "Симба Ролл",
    image: "/products/sushi.png",
    price: 979,
    oldPrice: null,
    group: [4],
    color: "#FFA07A",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "8 шт.", price: 979 }],
    extras: null,
    information: {
      id: 5,
      composition: "Рис, нори, сыр, лосось, огурец",
      description: "Набор роллов на 8 кусочков.",
      fats: 9,
      proteins: 13,
      carbohydrates: 28,
      calories: 240,
      gramm: "520 г",
    },
  },
  {
    id: 6,
    name: "Медовик",
    image: "/products/cake.png",
    price: 979,
    oldPrice: null,
    group: [5],
    color: "#DAA520",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "Порция", price: 979 }],
    extras: null,
    information: {
      id: 6,
      composition: "Медовые коржи, сливочный крем",
      description: "Классический десерт с насыщенным медовым вкусом.",
      fats: 12,
      proteins: 5,
      carbohydrates: 35,
      calories: 320,
      gramm: "520 г",
    },
  },
  {
    id: 7,
    name: "Римини Мини",
    image: "/products/pizza2.png",
    price: 979,
    oldPrice: null,
    group: [1],
    color: "#9ACD32",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "25 см", price: 979 }],
    extras: null,
    information: {
      id: 7,
      composition: "Тесто, соус, сыр, курица, овощи",
      description: "Небольшая пицца для одного.",
      fats: 9,
      proteins: 11,
      carbohydrates: 32,
      calories: 260,
      gramm: "520 г",
    },
  },
  {
    id: 8,
    name: "Соус Кетчуп",
    image: "/products/souse.png",
    price: 29,
    oldPrice: 39,
    group: [6],
    color: "#FF2424",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "50 г", price: 29 }],
    extras: null,
    information: {
      id: 8,
      composition: "Томатный соус",
      description: "Классический томатный кетчуп.",
      fats: 0,
      proteins: 1,
      carbohydrates: 8,
      calories: 35,
      gramm: "520 г",
    },
  },
  {
    id: 9,
    name: "Комбо Фри",
    image: "/products/fries.png",
    price: 179,
    oldPrice: 299,
    group: [11],
    color: "#FFD700",
    variant: "default",
    subgroup: ["Классика"],
    types: [{ id: 1, name: "Порция", price: 179 }],
    extras: null,
    information: {
      id: 9,
      composition: "Картофель фри, куриные наггетсы",
      description: "Хрустящий набор: фри и курочка.",
      fats: 15,
      proteins: 10,
      carbohydrates: 30,
      calories: 340,
      gramm: "520 г",
    },
  },
];
